--- # Credits https://github.com/StarterSquad/prudentia/blob/master/prudentia/tasks/ssl-self-certificate.yml
  - name: Self signed | Install last stable
    ansible.builtin.apt:
      update-cache: yes
      force: yes
      state: present
      pkg: openssl
    become: true

  - name: Self signed | Generate self signed passwordless certificate
    ansible.builtin.command: >
        openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509
        -subj "/C=EU/ST=Ukraine/L=Lviv/O=Dis/CN={{ fqdn }}"
        -keyout {{ key }}.key -out {{ crt }}.crt
    changed_when: false

  - name: Self signed | Move files to target dir
    ansible.builtin.command: mv -t {{ target_dir }} {{ key }}.key {{ crt }}.crt
    changed_when: false
    become: true
