---
  - name: USE | Detect upstart system
    ansible.builtin.shell: |
      if [[ `/sbin/init --version 2> /dev/null` =~ upstart ]]; then echo upstart;
      elif [[ `systemctl` =~ -\.mount ]]; then echo systemd;
      elif [[ -f /etc/init.d/cron && ! -h /etc/init.d/cron ]]; then echo sysv-init;
      else echo UNKNOWN;
      fi
    become: true
    changed_when: False
    args:
      executable: /bin/bash
    register: upstart_detect_raw

  - name: USE | Detect upstart system and set fact
    ansible.builtin.set_fact:
      upstart_system: "{{ upstart_detect_raw.stdout }}"
