---
# https://github.com/ribbybibby/ssl_exporter
# https://github.com/ribbybibby/ssl_exporter/releases/download/v0.5.0/ssl_exporter-0.5.0.linux-amd64.tar.gz
- name: Set exporter facts
  ansible.builtin.set_fact:
    ssl_exporter_sub_dir: "{{ exporter_config.exporter_dir | default('ssl_exporter') }}"
    ssl_exporter_user: "{{ exporter_config.exporter_user | default(prometheus_user) }}"
    ssl_exporter_group: "{{ exporter_config.exporter_group | default(prometheus_group) }}"

- name: Prometheus ssl exporter | check if this exporter version exists
  ansible.builtin.stat:
    path: "{{ prometheus_exporters_dir }}/ssl_exporter-{{ prometheus_ssl_exporter_version }}.linux-amd64/"
  register: ssl_exporter_version_exists
  become: true
  become_user: "{{ ssl_exporter_user }}"

- name: Prometheus ssl Exporter | Download distribution
  ansible.builtin.get_url:
    url: "https://github.com/ribbybibby/ssl_exporter/releases/download/v{{ prometheus_ssl_exporter_version }}/ssl_exporter-{{ prometheus_ssl_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/ssl_exporter-{{ prometheus_ssl_exporter_version }}.linux-amd64.tar.gz"
    owner: "{{ ssl_exporter_user }}"
    group: "{{ ssl_exporter_group }}"
    mode: "0644"
  become: true
  become_user: "{{ ssl_exporter_user }}"
  when: not ssl_exporter_version_exists.stat.exists
  tags:
    - prometheus

- name: Prometheus ssl Exporter | unpack distribution
  ansible.builtin.unarchive:
    src: "/tmp/ssl_exporter-{{ prometheus_ssl_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_exporters_dir }}"
    remote_src: true
  become: true
  become_user: "{{ ssl_exporter_user }}"
  when: not ssl_exporter_version_exists.stat.exists
  tags:
    - prometheus

- name: Prometheus ssl Exporter | link ssl exporter dir
  ansible.builtin.file:
    src: "{{ prometheus_exporters_dir }}/ssl_exporter-{{ prometheus_ssl_exporter_version }}.linux-amd64/"
    dest: "{{ prometheus_exporters_dir }}/{{ ssl_exporter_sub_dir }}"
    state: link
    owner: "root"
    group: "{{ ssl_exporter_group }}"
  become: true
  when: not ssl_exporter_version_exists.stat.exists
  tags:
    - prometheus

- name: Prometheus SSL Exporter | Include startup tasks
  ansible.builtin.include_tasks: "tasks_startup.yml"
  vars:
    exporter_startup_config: "{{ exporter_config }}"
