---
  - name: GO | Check if installed
    ansible.builtin.command: test -x /usr/local/go/bin/go
    ignore_errors: yes
    changed_when: False
    register: go_present
    tags:
      -go

  - name: Go | Download distribution
    ansible.builtin.get_url:
      url: "https://storage.googleapis.com/golang/go{{ go_version | default('1.6') }}.linux-amd64.tar.gz"
      dest: /tmp/go.tar.gz
      mode: '0644'
    when: go_present is failed
    tags:
      -go

  - name: Go | Unpack distribution
    ansible.builtin.unarchive:
      src: /tmp/go.tar.gz
      dest: /usr/local
      copy: no
    become: true
    when: go_present is failed
    tags:
      -go

  - name: GO | prepare /etc/profile.d/go_path.sh
    ansible.builtin.file:
      path: /etc/profile.d/go_path.sh
      state: touch
      mode: "u=rw,g=r,o=r"
    become: true
    tags:
      -go

  - name: Add the Go bin directory to the PATH environment variable for all users
    ansible.builtin.lineinfile:
      dest: /etc/profile.d/go_path.sh
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    become: true
#    when: go_present is failed
    with_items:
      - {regexp: "^export PATH=.*", line: "export PATH=$PATH:/usr/local/go/bin"}
    tags:
      -go


  - name: Set GOPATH for all users
    ansible.builtin.lineinfile:
      dest: /etc/profile.d/go_path.sh
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - {regexp: "^export GOPATH=.*", line: "export GOPATH=/usr/local/go"}
      - {regexp: "^export PATH=.*", line: "export PATH=$GOPATH/bin:$PATH"}
    become: true
#    when: go_present is failed
    tags:
      -go
