---
- hosts: prometheus_exporters
  gather_facts: False

  vars:
    - root_dir: ..

    - box_prometheus_exporters:

        - {
            name: node
          }
#        - {
#            name: cloudwatch
#          }
#        - {
#            name: phpfpm
#          }
#        - {
#            name: blackbox
#          }
#        - {
#            name: elasticsearch
#          }
#        - {
#            name: postgres
#          }
#        - {
#            name: cadvisor
#          }
#        - {
#            name: mongodb
#          }
#        - {
#            name: monit,
#            monit_user: "admin",
#            monit_password: "xeR5hSdSQcCnFVLV8PLy",
#            listen_address: "0.0.0.0:9388"
#          }
#        - {
#            name: redis
#          }
#        - {
#            name: sql
#          }
#        - {
#            name: memcached
#          }
#        - {
#            name: mysqld
#          }
#        - {
#            name: ecs,
#            parameters: "--aws.region='us-east-1'"
#          }



  pre_tasks:
    - ansible.builtin.debug: msg="Pre tasks section"

    - name: ANSIBLE PYTHON | install python 2
      raw: test -e /usr/bin/python || test -e /usr/bin/python3 || (apt -qqy update && apt install -qy python-minimal)
      become: true

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      ansible.builtin.apt: pkg="acl"
      become: true

    - name: gather facts
      setup:
      tags: always


  roles:
    #  - {
    #      role: "sa-monit",
    #      tags: ["create"],
    #    }

     - {
         role: "sa-prometheus-exporters",
         tags: ["create"],
         prometheus_exporters: "{{box_prometheus_exporters}}"
       }

  tasks:

    - ansible.builtin.debug: msg="Tasks section"
