---
- hosts: www
  gather_facts: False

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

    - name: ANSIBLE PYTHON | install python 2
      raw: test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)
      become: yes

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      apt: pkg="acl"
      become: yes

    - name: gather facts
      setup:
      tags: always


  roles:
     - {
         role: "sa-prometheus-exporters",
         tags: ["create"]
       }

  tasks:

    - debug: msg="Tasks section"
