# respect historical role name with dash
role_name_check: 1
driver:
  name: vagrant
  provider:
    # Can be any supported provider (virtualbox, parallels, libvirt, etc)
    # Defaults to virtualbox
    name: virtualbox
  # Run vagrant up with --provision.
  # Defaults to --no-provision)
  provision: false
  # vagrant-cachier configuration
  # Defaults to 'machine'
  # Any value different from 'machine' or 'box' will disable it
  cachier: machine
  # If set to false, set VAGRANT_NO_PARALLEL to '1'
  # Defaults to true - but that can cause issues with multiple machines
  parallel: false
  default_box: 'ubuntu/jammy64'
platforms:
  - name: ubuntu2204
    box: ubuntu/jammy64
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
    instance_raw_config_args:
      - "vbguest.auto_update = false"   # yamllint disable-line
      - "disksize.size = '50GB'"
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
  - name: debian
    box: debian/bullseye64
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true
    instance_raw_config_args:
      - "vbguest.auto_update = false"   # yamllint disable-line
      - "disksize.size = '50GB'"
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
  # - name: alpine
  #   box:  generic/alpine318
  #   memory: 4096
  #   cpus: 2
  #   interfaces:
  #     - network_name: private_network
  #       type: dhcp
  #       auto_config: true
  #   instance_raw_config_args:
  #     - "vbguest.auto_update = false"   # yamllint disable-line
  #     - "disksize.size = '50GB'"
  #   provider_raw_config_args:
  #     - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
provisioner:
  name: ansible
  log: true
  scenario:
    name: default
  config_options:
    defaults:
      allow_world_readable_tmpfiles: true
      callback_whitelist: profile_roles,profile_tasks,timer
      # https://github.com/ansible/ansible/issues/40208
      # https://github.com/ansible-community/molecule/issues/249
      # https://github.com/ansible-community/molecule/issues/2626
      ansible_python_interpreter: /usr/bin/python3
